variables:
  STACK_ROOT: "${CI_PROJECT_DIR}/.stack"

stages:
  - build
  - build-image

build:
  stage: build
  image: fpco/stack-build:latest
  script:
    - rm stack.yaml.lock  # workaround
    - apt update -y  # workaround for weird certificate error, should be removed soon
    - apt upgrade -y
    - stack build
    - cp $(stack path --local-install-root)/bin/mock-bot-telegram .
  artifacts:
    paths:
      - mock-bot-telegram
  cache:
    paths:
      - .stack-work
      - .stack

build-image:
  stage: build-image
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mv mock-bot-telegram docker/
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR/docker --dockerfile $CI_PROJECT_DIR/docker/dockerfile --destination $CI_REGISTRY_IMAGE:latest
