name:                mockerell
version:             0.4.0
license:             WTFPL
git:                 "https://github.com/zoomoid/mockerell"
author:              "Nicolas Lenz"
maintainer:          "Alexander Bartolomey <occloxium@gmail.com>"
copyright:           "2021 Alexander Bartolomey"

extra-source-files:
- README.md

synopsis:            tELegrAm bOT fOR mOCKiNg
category:            Web
description:         A telegram bot for mocking with haskell

dependencies:
- base
- telegram-bot-simple
- mock
- text
- mtl
- cryptonite
- memory
- classy-prelude
- aeson

default-extensions:
- LambdaCase
- OverloadedStrings
- NoImplicitPrelude

executables:
  mock-bot-telegram:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
