apiVersion: apps/v1
kind: Deployment
metadata:
  name: mockerellbot
  labels:
    app.kubernetes.io/name: mockerellbot
    app.kubernetes.io/created-by: zoomoid
spec:
  selector:
    matchLabels:
      app.kubernetes.io/app: mockerellbot
  template:
    metadata:
      labels:
        app.kubernetes.io/app: mockerellbot
    spec:
      containers:
      - name: mockerellbot
        env:
          - name: MOCK_BOT_TOKEN
            valueFrom:
                secretKeyRef:
                  name: mockerellbot-token
                  key: MOCK_BOT_TOKEN
                  optional: true
        image: ghcr.io/zoomoid/mockerell:edge
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"
