apiVersion: apps/v1
kind: Deployment
metadata:
  name: mockerellbot
  labels:
    app.kubernetes.io/name: mockerellbot
    app.kubernetes.io/created-by: zoomoid
spec:
  selector:
    matchLabels:
      app.kubernetes.io/app: mockerellbot
  template:
    metadata:
      labels:
        app.kubernetes.io/app: mockerellbot
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: mockerellbot
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - "ALL"
        env:
          - name: MOCK_BOT_TOKEN
            valueFrom:
                secretKeyRef:
                  name: mockerellbot-token
                  key: MOCK_BOT_TOKEN
                  optional: false
        image: ghcr.io/zoomoid/mockerell:latest
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"
